# Generated by Django 5.1.2 on 2024-10-28 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentSupplyDemand',
            fields=[
                ('baseDatetime', models.DateTimeField(primary_key=True, serialize=False)),
                ('suppAbility', models.FloatField(default=0.0)),
                ('currPwrTot', models.FloatField(default=0.0)),
                ('forecastLoad', models.FloatField(default=0.0)),
                ('suppReservePwr', models.FloatField(default=0.0)),
                ('suppReserveRate', models.FloatField(default=0.0)),
                ('operReservePwr', models.FloatField(default=0.0)),
                ('operReserveRate', models.FloatField(default=0.0)),
            ],
        ),
    ]
