# Generated by Django 5.1.2 on 2024-10-28 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplydemand', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currentsupplydemand',
            old_name='baseDatetime',
            new_name='index',
        ),
    ]
