# Generated by Django 5.1.2 on 2024-10-29 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplydemand', '0003_alter_currentsupplydemand_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiveMinSupplyDemand',
            fields=[
                ('baseDatetime', models.TextField(primary_key=True, serialize=False)),
                ('suppAbility', models.FloatField(default=0.0)),
                ('currPwrTot', models.FloatField(default=0.0)),
                ('forecastLoad', models.FloatField(default=0.0)),
                ('suppReservePwr', models.FloatField(default=0.0)),
                ('suppReserveRate', models.FloatField(default=0.0)),
                ('operReservePwr', models.FloatField(default=0.0)),
                ('operReserveRate', models.FloatField(default=0.0)),
            ],
        ),
    ]
