# Generated by Django 5.1.2 on 2024-10-29 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplydemand', '0004_fiveminsupplydemand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currentsupplydemand',
            old_name='index',
            new_name='baseDatetime',
        ),
    ]
