# Generated by Django 5.1.2 on 2024-10-29 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplydemand', '0005_rename_index_currentsupplydemand_basedatetime'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FiveMinSupplyDemand',
            new_name='FiveMSupplyDemand',
        ),
        migrations.DeleteModel(
            name='CurrentSupplyDemand',
        ),
    ]
